name: project_environment
dependencies:
  # The python interpreter version.

  # Currently Azure ML only supports 3.5.2 and later.

- python=3.6.2

- pip:
  - azureml-defaults
  - azureml-train-automl
- numpy
- scikit-learn
- conda-forge::fbprophet==0.5

